layout_spectrum: 0.2808511
typography_spectrum: 1
color:
  lightness: 0.02978723
  brandStrength: 0.3133602
  saturation: 0.2808511
  rhythmicContrast: 0.8
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: leal
